### ISSUE TITLE
Updating localtuya switch took longer than the scheduled update interval 0:00:30.

### ISSUE THREAD

**Issue by FeromonDE** [rospogrigio/localtuya-homeassistant#53]
Hi, i have BW-SHP6 Plug with PM, after Update to HA 0.115.2 i have a problem.

2020-09-22 14:58:15 WARNING (MainThread) [homeassistant.components.switch] Updating localtuya switch took longer than the scheduled update interval 0:00:30.

I can not control the plug. After HA reboot is everything working as it shoud.

**Comment by rospogrigio** [comment]
What rev. of localtuya are you using? The latest release? 
Please wait some more days, we are doing a huge code refactoring, and something cool and stable will be ready quite soon I hope...

**Comment by rocksolid2018** [comment]
Same issue here current localtuua v1,2,0. restarting HA fixes the issue temporally

**Comment by FeromonDE** [comment]
> What rev. of localtuya are you using? The latest release?
> Please wait some more days, we are doing a huge code refactoring, and something cool and stable will be ready quite soon I hope...
current localtuya v1.2.0

**Comment by rospogrigio** [comment]
Well everything is being refactored very hard at the moment, you should try what is in master now (but you have to modify the YAML heavily, or use the config flow), or wait for the next big release, which should be ready quite soon.

**Comment by DSchumacher2104** [comment]
If i want to use the current master with config flow, i only have to put 'localtuya:' in configuration.yaml, right?

**Comment by postlund** [comment]
> If i want to use the current master with config flow, i only have to put 'localtuya:' in configuration.yaml, right?

Yeah!

**Comment by postlund** [comment]
@FeromonDE Maybr you can retry with latest version and see if problem still exists?

**Comment by FeromonDE** [comment]
There is no problem anymore with latest version.
