### ISSUE TITLE
Component error: localtuya - No module named 'homeassistant.helpers.reload'

### ISSUE THREAD

**Issue by rocksolid2018** [rospogrigio/localtuya-homeassistant#67]
Updated to 2.0.1, unable to detected plug via yaml method or integration method.

Error while checking config file: Component error: localtuya - No module named 'homeassistant.helpers.reload'

Last working version: 1.2.0

**Comment by andrewmeepos** [comment]
@rospogrigio @postlund Getting this error on 2.0.1 as well.

**Comment by postlund** [comment]
I believe this feature was added in Home Assistant 0.115. Try upgrading, that should solve the problem.

**Comment by andrewmeepos** [comment]
Yup, that fixed it. Thanks!
