### ISSUE TITLE
Failed to authenticate with Tuya Switch

### ISSUE THREAD

**Issue by quangvinh9x** [rospogrigio/localtuya-homeassistant#68]
Thanks for your custom component.
I have a problem when add Tuya switch by Tuyalocal:

1. Home Assistant 0.115.6
2. LocalTuya: lastest release.
3. Yesterday, i add an Tuya 2 Gang switch to my HA (I had localkey an DevID) and it worked.
4. Today, i changed my router (because i go to my farther-in-law house), when i add Tuya device, system noti: Failed to authenticate with device. Verify that device id and local key are correct.
![Screenshot 2020-10-05 200415](https://user-images.githubusercontent.com/71742958/95082978-12d53580-0746-11eb-9fec-fc4485dbe1e4.jpg)
Log: "
Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:273
Integration: localtuya (documentation)
First occurred: 7:57:12 PM (3 occurrences)
Last logged: 8:05:42 PM

Failed to get status: 'utf-8' codec can't decode byte 0xdf in position 0: invalid continuation byte
Failed to get status: [Errno 104] Connection reset by peer
Failed to get status: Expecting value: line 1 column 1 (char 0)"
Anyone can help me?
Thanks!

**Comment by postlund** [comment]
If you provisioned the device to a new access point, the device will generate a new local key. So you will need to get the new local key for this to work.

**Comment by quangvinh9x** [comment]
Thank you! I am trying to generate a new local key.
I do like this video to generate a local key, but it like the last local key i generate in old device.

**Comment by postlund** [comment]
I've only retrieved the local key as described at tuyapi, by signing up for a developer account. I don't use any app, only Home Assistant. So I'm not of much help here I'm afraid 😟

**Comment by postlund** [comment]
Anything more we can help with here or is the issue done?

**Comment by quangvinh9x** [comment]
Thank you very much. I removed switch from HASS, after i used local tuya to add it.
it worked great.
That amazing.

**Comment by postlund** [comment]
Great! 👍
