### ISSUE TITLE
[FEATURE] Polling Interval

### ISSUE THREAD

**Issue by SPDurkee** [rospogrigio/localtuya-homeassistant#71]
There doesn't seem to be a way to set the poling rate, which currently seems to be every 30 seconds. With 15 devices, and async not working yet, it takes quite a toll on the server.

Can you add a poll_interval property or something similar? Thank you!

**Comment by postlund** [comment]
We will merge #62 soon, so adding that would just mean more overhead in development. @rospogrigio Any problems on your end worth taking actions on before merging #62?

**Comment by SPDurkee** [comment]
In case anyone else is interested: As a temporary workaround, you can edit line # 72 in __init__.py
`POLL_INTERVAL = 60`

**Comment by rospogrigio** [comment]
> We will merge #62 soon, so adding that would just mean more overhead in development. @rospogrigio Any problems on your end worth taking actions on before merging #62?

Just added a comment there...

**Comment by rospogrigio** [comment]
Closing issue since #62 will fix it.
