### ISSUE TITLE
Changing the brightness parameter.

### ISSUE THREAD

**Issue by Securond** [rospogrigio/localtuya-homeassistant#73]
Hi, I have a Tuya dimmer in which the brightness is 0-1000, but the integration allows you to change the brightness only from 0-255 and the lamp glows dimly. can I add the ability to change this parameter ?

dps: { '20': false, '21': 'white', '22': 1000, '26': 0 }

**Comment by postlund** [comment]
Yeah, this has been reported on the community forums as well and we should definitely fix this. I have not started yet, so if anyone wants to do that feel free to do so.

**Comment by postlund** [comment]
Please give #80 and try, it should solve this i hope. You can specify lower and upper limits and the value from home assistant (0-255) will be mapped to this range.

**Comment by Securond** [comment]
In the latest version, I get this error.

Source: custom_components/localtuya/light.py:91
First occurred: 17:00:35 (1 occurrences)
Last logged: 17:00:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 442, in state_attributes
    data[ATTR_COLOR_TEMP] = self.color_temp
  File "/config/custom_components/localtuya/light.py", line 91, in color_temp
    return int(MAX_MIRED - (((MAX_MIRED - MIN_MIRED) / 255) * self._color_temp))
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by Securond** [comment]
When adding the device, I did not configure "COLOR_TEMP", left this field empty and now EVERYTHING works as it should, without errors. ))

**Comment by postlund** [comment]
Yeah, I'm using the approach that if you configure something it is assumed to be supported by the device (since we can't really deduce that in a decent way). In the future you will be able to unset options so you don't have to remove and re-add. But that's how it works now.

**Comment by postlund** [comment]
Also, maybe we can close this issue then?
